image: python:3

lint:
 stage: test
 script:
 - pip install yapf
 - yapf --recursive .
 only:
 - pushes

unittest:
 stage: test
 script:
  - pip install -r requirements.txt
  - pytest .
 only:
  - merge_requests